### ISSUE TITLE
[BUG] GitQLient segfault with qtermwidget-1.4.0

### ISSUE THREAD

**Issue by band-a-prend** [francescmm/GitQlient#285]
**Describe the bug**
GitQLient successfully run and open repo when qtermwidget-1.3.0 is installed as system package but get segfault with qtermwidget-1.4.0:

```
...
Thread 1 "gitqlient" received signal SIGSEGV, Segmentation fault.
0x000000000049719f in ConfigWidget::loadPlugins (this=this@entry=0x1029300, plugins=...) at src/big_widgets/ConfigWidget.cpp:614
warning: 614    src/big_widgets/ConfigWidget.cpp: No such file or directory
(gdb) bt
#0  0x000000000049719f in ConfigWidget::loadPlugins (this=this@entry=0x1029300, plugins=...) at src/big_widgets/ConfigWidget.cpp:614
#1  0x00000000004bff9e in GitQlientRepo::setPlugins (this=this@entry=0x1143010, plugins=...) at src/big_widgets/GitQlientRepo.cpp:219
#2  0x00000000004b2525 in GitQlient::addNewRepoTab (this=this@entry=0x7fffffffd7a0, repoPathArg=..., pinned=pinned@entry=false) at src/big_widgets/GitQlient.cpp:410
#3  0x00000000004b3f74 in GitQlient::addRepoTab (this=0x7fffffffd7a0, repoPath=...) at src/big_widgets/GitQlient.cpp:352
#4  0x00007ffff6e73ae1 in ?? () from /usr/lib64/libQt5Core.so.5
#5  0x000000000059e1d6 in InitScreen::signalOpenRepo (this=<optimized out>, _t1=...) at moc_InitScreen.cpp:165
#6  0x00007ffff6e73ae1 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007ffff7a7c188 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff7b296be in QFrame::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff7a385fe in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff7a40d6b in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff6e3e978 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#12 0x00007ffff7a3f003 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff7a95e5f in ?? () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff7a99237 in ?? () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff7a385fe in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff6e3e978 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#17 0x00007ffff73fc7db in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
#18 0x00007ffff73d9ec3 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
#19 0x00007ffff32640ba in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#20 0x00007ffff588333c in ?? () from /usr/lib64/libglib-2.0.so.0
#21 0x00007ffff58865d7 in ?? () from /usr/lib64/libglib-2.0.so.0
#22 0x00007ffff5886bec in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#23 0x00007ffff6e934ea in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#24 0x00007ffff6e3d22b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#25 0x00007ffff6e45ab1 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#26 0x000000000045d7cf in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:39
(gdb) 
```

**To Reproduce**
1. Install qtermwidget-1.3.0
2. Start gitqlient, open repo, go to Config tab -> Plugins -> Plugins folder. 
3. Set "/usr/lib64" or directory where qtermwidget-1.3.0 library is installed.
4. Restart GitQlient, open repo and notice that it's ok
5. Install qtermwidget-1.4.0
6. Launch GitQlient and open repo
7. Notice the segfault of application.

With qtermwidget built from upstream developer branch (commit 72b118) there is no segfault but GitQlient doesn't see plugin library as does it with qtermwidget-1.3.0.

**Expected behavior**
After open repo the main window with commits is shown and qterm plugin is available to switch on in settings and could be enabled to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Release version or SHA: 1.6.2 or 58b87fb
 - If manually compiled, compiler version: 1.6.2 or 58b87fb

**Additional context**
none

**Comment by francescmm** [comment]
Thanks for reporting @band-a-prend!

I'm thinking on dropping the support for this feature since it's quite difficult to maintain and it won't be necessary now for when I release the plugin for QtCreator.

**Comment by francescmm** [comment]
After some consideration, I've decided to remove this plugin and simplify GitQlient.
